package io.github.cliproxy.android;

import android.content.Context;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.util.Locale;

public final class AppPaths {
    private AppPaths() {}

    public static File root(Context c) { return new File(c.getFilesDir(), "cpa"); }
    public static File authDir(Context c) { return new File(root(c), "auths"); }
    public static File logDir(Context c) { return new File(root(c), "logs"); }
    public static File staticDir(Context c) { return new File(root(c), "static"); }
    public static File config(Context c) { return new File(root(c), "config.yaml"); }
    public static File wrapperLog(Context c) { return new File(logDir(c), "android-wrapper.log"); }
    public static File managementHtml(Context c) { return new File(staticDir(c), "management.html"); }
    public static File nativeBinary(Context c) { return new File(c.getApplicationInfo().nativeLibraryDir, "libcliproxyapi.so"); }

    public static synchronized void ensureWorkspace(Context c) throws IOException {
        mkdir(root(c));
        mkdir(authDir(c));
        mkdir(logDir(c));
        mkdir(staticDir(c));

        if (!managementHtml(c).isFile()) {
            copyAsset(c, "cpa/management.html", managementHtml(c));
        }
        if (!config(c).isFile()) {
            writeDefaultConfig(c);
        }
    }

    private static void mkdir(File dir) throws IOException {
        if (!dir.isDirectory() && !dir.mkdirs()) {
            throw new IOException("Unable to create directory: " + dir);
        }
    }

    private static void copyAsset(Context c, String assetName, File out) throws IOException {
        try (InputStream in = c.getAssets().open(assetName); FileOutputStream fos = new FileOutputStream(out)) {
            byte[] buf = new byte[64 * 1024];
            int n;
            while ((n = in.read(buf)) >= 0) fos.write(buf, 0, n);
        }
    }

    private static void writeDefaultConfig(Context c) throws IOException {
        String apiKey = randomHex(24);
        String admin = randomHex(18);
        String auth = authDir(c).getAbsolutePath().replace("\\", "/");
        c.getSharedPreferences("secrets", Context.MODE_PRIVATE).edit().putString("management_plaintext", admin).apply();
        String yaml = """
                # Generated by CLIProxyAPI Android GUI. The WebUI and raw YAML editor can modify this file.
                config-version: 8
                server:
                  host: "0.0.0.0"
                  port: 8317
                  trusted-proxies: []
                  commercial-mode: false
                  discovery:
                    enabled: false
                management:
                  allow-remote: false
                  secret-key: "%s"
                  disable-control-panel: false
                  disable-auto-update-panel: false
                  panel-github-repository: "https://github.com/router-for-me/Cli-Proxy-API-Management-Center"
                access:
                  api-keys:
                    - "%s"
                routing:
                  strategy: "round-robin"
                  session-affinity: false
                  session-affinity-ttl: "1h"
                  session-affinity-subagents: true
                  force-model-prefix: false
                  retry:
                    request-retry: 3
                    max-retry-credentials: 0
                    max-retry-interval: 30
                  cooldown:
                    disable-cooling: false
                    save-cooldown-status: false
                    transient-error-cooldown-seconds: 0
                requests:
                  proxy-url: ""
                  passthrough-headers: false
                  nonstream-keepalive-interval: 0
                  streaming:
                    keepalive-seconds: 0
                    bootstrap-retries: 0
                oauth:
                  auth-dir: "%s"
                observability:
                  logs:
                    debug: false
                    logging-to-file: true
                    logs-max-total-size-mb: 25
                    error-logs-max-files: 10
                    request-log: false
                  usage:
                    usage-statistics-enabled: true
                    redis-usage-queue-retention-seconds: 60
                """;
        yaml = String.format(Locale.US, yaml, admin, apiKey, auth);
        try (FileOutputStream out = new FileOutputStream(config(c))) {
            out.write(yaml.getBytes(StandardCharsets.UTF_8));
        }
    }

    private static String randomHex(int bytes) {
        byte[] data = new byte[bytes];
        new SecureRandom().nextBytes(data);
        StringBuilder s = new StringBuilder(bytes * 2);
        for (byte b : data) s.append(String.format("%02x", b & 0xff));
        return s.toString();
    }
}
